EDUFLEX/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
urlpatterns = [
    path('',include('accounts.urls',namespace='accounts')),
    path('',include('PADRE.urls',namespace='padre')),
    path('',include('PROFESOR.urls',namespace='profesor')),
    path('',include('NIÑO.urls',namespace='niño')),
    path('admin/', admin.site.urls)
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NIÑO/urls.py
from django.urls import path
from NIÑO.views import *

app_name = 'niño'

urlpatterns = [
    path('dashboardKid/', DashboardKid.as_view(), name='dashboardKid'),
    path('juegos_recomendados/', JuegosRecomendadosView.as_view(), name='juegos_recomendados'),
    path('niveles_disgrafia/', niveles_disgrafiaView.as_view(), name='niveles_disgrafia'),
    path('juego_completar/', juego_completar_palabraView.as_view(), name='completar_palabra'),
    path('guardar_progreso/', GuardarProgresoView.as_view(), name='guardar_progreso'),
    path('guardar_progreso_cartas/', GuardarProgresoCartasView.as_view(), name='guardar_progreso_cartas'),
    path('juego_cartas/', juego_cartasView.as_view(), name='juego_cartas'),
    path('niveles_cartas/', NivelesCartasView.as_view(), name='niveles_cartas'),
    path('preferencias/', PreferenciasUsuarioView.as_view(), name='preferencias'),
    path('editar-perfil/', EditarPerfilView.as_view(), name='editar_perfil'),
    path('guardar_progreso_multiplicacion/', GuardarProgresoMultiplicacionView.as_view(), name='guardar_progreso_multiplicacion'),
    path('juego_multiplicacion/', JuegoMultiplicacionView.as_view(), name='juego_multiplicacion'),
    path('niveles_discalculia/', NivelesDiscalculiaView.as_view(), name='niveles_discalculia'),
    path('cerrar_juego/', cerrar_juegoView.as_view(), name='cerrar_juego'),
]

accounts/urls.py
from django.urls import path
from accounts.views import *
app_name = 'accounts'
urlpatterns = [
path('',HomePageView.as_view(),name='home'),
path('login/',LoginView.as_view(),name='login'),
path('logout/',LogoutView.as_view(),name='logout'),
path('rol/',RolView.as_view(),name='rol'),
path('signupkid/',SignupKidView.as_view(),name='signupkid'),
path('signupdad/',SignupDadView.as_view(),name='signupdad'),
path('recuperar/<str:rol>/', EnviarCodigoView.as_view(), name='recover_password'),
path('verificar/', VerificarCodigoView.as_view(), name='verificar_codigo'),
path('cambiar/', CambiarContraseñaConCodigoView.as_view(), name='cambiar_contraseña')
]

NIÑO/models.py
from django.contrib.auth.models import User
from django.db import models
from storages.backends.s3boto3 import S3Boto3Storage

from PADRE.models import Padre
SEX_CHOICES=[('M', 'Masculino'), ('F', 'Femenino')]
ESPECIALIDAD=[('D','Disgrafia'),('T','TDA'),('DC','Discalculia')]

class ProfilePictureStorage(S3Boto3Storage):
    location = 'profile_pictures'
    default_acl = 'public-read'
    file_overwrite = False

class Niño(models.Model):
    codigo = models.CharField(max_length=10, unique=True, null=True, blank=True)
    nombres=models.CharField(max_length=100)
    apellidos=models.CharField(max_length=100)
    genero=models.CharField(max_length=1,choices=SEX_CHOICES)
    usuario=models.CharField(max_length=30)
    contraseña = models.CharField(max_length=64)
    fecha_nac=models.DateField()
    email=models.EmailField()
    foto_perfil=models.ImageField(upload_to="perfiles/", storage=ProfilePictureStorage,blank=True,null=True)
    especialidad=models.CharField(max_length=2,choices=ESPECIALIDAD)
    padre = models.ForeignKey(Padre, on_delete=models.SET_NULL, null=True, blank=True, related_name='hijos')
    @property
    def nombre_completo(self):
        return f"{self.nombres} {self.apellidos}"

    def __str__(self):
        return f"{self.nombres} {self.apellidos}"

    def get_image(self):
        if self.foto_perfil:
            return self.foto_perfil.url

class Reporte(models.Model):
    niño = models.ForeignKey(Niño, on_delete=models.CASCADE, related_name='reportes', null=True, blank=True)
    titulo = models.CharField(max_length=100, null=True, blank=True)
    puntaje = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    distracciones = models.IntegerField(null=True, blank=True, help_text="Cantidad de distracciones detectadas")
    somnolencias = models.IntegerField(null=True, blank=True)
    tiempos_somnolencia = models.JSONField(null=True, blank=True)
    tiempos_distraccion = models.JSONField(null=True, blank=True)
    frames_somnolencia = models.JSONField(null=True, blank=True)
    frames_distraccion = models.JSONField(null=True, blank=True)
    fecha = models.DateField(auto_now=True,null=True, blank=True)
    duracion_evaluacion = models.DurationField(null=True, blank=True, help_text="Duración total de la evaluación")
    comentario = models.TextField(max_length=500, null=True, blank=True)

class ProgresoNiño(models.Model):
    niño = models.OneToOneField(Niño, on_delete=models.CASCADE, related_name='progreso')
    nivel_desbloqueado = models.IntegerField(default=1)
    puntaje_total = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    tiempo_total = models.IntegerField(default=0)

    def __str__(self):
        return f"Progreso de {self.niño.nombre_completo}"


class ProgresoCartas(models.Model):
    niño = models.OneToOneField(Niño, on_delete=models.CASCADE)
    nivel_desbloqueado = models.IntegerField(default=1)
    puntaje_total = models.IntegerField(default=0)
    tiempo_total = models.IntegerField(default=0)

    def __str__(self):
        return f"Progreso Cartas de {self.niño.nombre_completo}"


class ProgresoDiscalculia(models.Model):
    niño = models.OneToOneField(Niño, on_delete=models.CASCADE)
    nivel_desbloqueado = models.IntegerField(default=1)
    puntaje_total = models.IntegerField(default=0)
    tiempo_total = models.IntegerField(default=0)

    def __str__(self):
        return f"Progreso Discalculia de {self.niño.nombre_completo}"


class PreferenciasUsuario(models.Model):
    niño = models.OneToOneField(Niño, on_delete=models.CASCADE, related_name='preferencias')
    sonido_activado = models.BooleanField(default=True)
    texto_grande = models.BooleanField(default=False)
    actualizado = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Preferencias de {self.niño.nombre_completo}"

NIÑO/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.views import View
from django.views.generic import TemplateView
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from decimal import Decimal
from .models import ProgresoNiño
from NIÑO.models import Niño,Reporte
from threading import Thread
from NIÑO.modelo_deteccion import resultado_final,gen_frames_background,stop_event,deteccion_finalizada
from datetime import datetime
from datetime import timedelta
from .models import ProgresoNiño, ProgresoCartas,ProgresoDiscalculia
from .models import PreferenciasUsuario
from django.core.validators import validate_email
from django.core.exceptions import ValidationError



class DashboardKid(TemplateView):
    template_name = 'dashboardKid.html'

    def dispatch(self, request, *args, **kwargs):
        if 'nino_id' not in request.session:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    @staticmethod
    def formatear_tiempo(td: timedelta) -> str:
        total_segundos = int(td.total_seconds())
        horas = total_segundos // 3600
        minutos = (total_segundos % 3600) // 60
        segundos = total_segundos % 60

        partes = []
        if horas > 0:
            partes.append(f"{horas}h")
        if minutos > 0 or horas > 0:
            partes.append(f"{minutos}m")
        partes.append(f"{segundos}s")

        return " ".join(partes)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        nino_id = self.request.session.get('nino_id')
        niño = Niño.objects.get(pk=nino_id)
        context['niño'] = niño

        total_niveles = 5


        if niño.especialidad == 'T':
            progreso = ProgresoCartas.objects.filter(niño=niño).first()
        else:
            progreso = ProgresoNiño.objects.filter(niño=niño).first()

        nivel_desbloqueado = progreso.nivel_desbloqueado if progreso else 1


        reportes_validos = Reporte.objects.filter(niño=niño, puntaje__gte=70)

        niveles_completados = set()
        records_dict = {}

        for rep in reportes_validos:
            try:
                nivel = int(rep.titulo.split()[-1])
            except:
                continue

            niveles_completados.add(nivel)

            if nivel not in records_dict:
                records_dict[nivel] = {
                    'nivel': nivel,
                    'puntaje': int(rep.puntaje),
                    'tiempo': self.formatear_tiempo(rep.duracion_evaluacion),
                    'duracion': rep.duracion_evaluacion
                }
            else:
                record_actual = records_dict[nivel]
                puntaje_actual = record_actual['puntaje']
                duracion_actual = record_actual['duracion']

                nuevo_puntaje = int(rep.puntaje)
                nueva_duracion = rep.duracion_evaluacion

                if (
                        nuevo_puntaje > puntaje_actual
                        or (nuevo_puntaje == puntaje_actual and nueva_duracion < duracion_actual)
                ):
                    records_dict[nivel] = {
                        'nivel': nivel,
                        'puntaje': nuevo_puntaje,
                        'tiempo': self.formatear_tiempo(nueva_duracion),
                        'duracion': nueva_duracion
                    }

        niveles_completados_count = len(niveles_completados)
        progreso_porcentaje = int((niveles_completados_count / total_niveles) * 100)


        records = sorted([
            {k: v for k, v in record.items() if k != 'duracion'}
            for record in records_dict.values()
        ], key=lambda x: x['nivel'])

        context.update({
            'niño': niño,
            'progreso_completado': niveles_completados_count,
            'total_niveles': total_niveles,
            'progreso_porcentaje': progreso_porcentaje,
            'records': records,
            'niveles_completados': niveles_completados_count
        })

        return context


class JuegosRecomendadosView(View):
    def dispatch(self, request, *args, **kwargs):
        if 'nino_id' not in request.session:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        nino_id = request.session.get('nino_id')

        if not nino_id:
            return redirect('accounts:login')

        try:
            nino = get_object_or_404(Niño, pk=nino_id)
            especialidad_niño = nino.especialidad

            juego_a_mostrar = None

            if especialidad_niño == 'D':
                juego_a_mostrar = "Ordena las palabras"
            elif especialidad_niño == 'DC':
                juego_a_mostrar = "Cuenta conmigo"
            elif especialidad_niño == 'T':
                juego_a_mostrar = "Desafío de concentración"

            return render(request, 'juegos.html', {'juego': juego_a_mostrar})

        except Niño.DoesNotExist:
            return render(request, 'juegos.html', {'juego': None})


class niveles_disgrafiaView(View):
    def get(self, request):
        nino_id = request.session.get('nino_id')
        if not nino_id:
            return redirect('accounts:login')
        niño = Niño.objects.get(pk=nino_id)
        progreso, _ = ProgresoNiño.objects.get_or_create(niño=niño)
        return render(request, 'niveles_disgrafia.html', {
            'nivel_desbloqueado': progreso.nivel_desbloqueado
        })


class juego_completar_palabraView(TemplateView):
    template_name = 'completar_palabra.html'

    def dispatch(self, request, *args, **kwargs):
        nino_id = request.session.get('nino_id')
        if not nino_id:
            return redirect('accounts:login')

        session_key = f"deteccion_iniciada_{nino_id}"
        tiempo_key = f"tiempo_inicio_deteccion_{nino_id}"

        iniciado = request.session.get(session_key, False)
        tiempo_inicio_str = request.session.get(tiempo_key)


        if iniciado and tiempo_inicio_str:
            try:
                tiempo_inicio = datetime.fromisoformat(tiempo_inicio_str)
                if datetime.now() - tiempo_inicio > timedelta(minutes=2):
                    iniciado = False
                    request.session[session_key] = False
                    request.session.pop(tiempo_key, None)
            except Exception:
                iniciado = False
                request.session[session_key] = False
                request.session.pop(tiempo_key, None)

        if not iniciado:
            request.session[session_key] = True
            request.session[tiempo_key] = datetime.now().isoformat()


            niño = Niño.objects.get(pk=nino_id)
            nuevo_reporte = Reporte.objects.create(niño=niño)
            request.session['reporte_id'] = nuevo_reporte.id

            def run_detection():
                gen_frames_background(nino_id, nuevo_reporte.id)

            t = Thread(target=run_detection)
            t.daemon = True
            t.start()

        return super().dispatch(request, *args, **kwargs)



@method_decorator(csrf_exempt, name='dispatch')
class GuardarProgresoView(View):
    def dispatch(self, request, *args, **kwargs):
        if 'nino_id' not in request.session:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)
    def post(self, request):
        nino_id = request.session.get('nino_id')
        if not nino_id:
            return JsonResponse({}, status=204)

        try:
            nivel = int(request.POST.get('nivel', 0))
            puntaje = Decimal(request.POST.get('puntaje', '0'))
            tiempo = int(request.POST.get('tiempo', 0))
            puntaje_real = Decimal(puntaje)

            niño = Niño.objects.get(pk=nino_id)
            progreso, _ = ProgresoNiño.objects.get_or_create(niño=niño)


            if puntaje >= 70:
                if nivel + 1 > progreso.nivel_desbloqueado:
                    progreso.nivel_desbloqueado = nivel + 1

            progreso.puntaje_total += puntaje
            progreso.tiempo_total += tiempo
            progreso.save()

            reporte_id = request.session.get('reporte_id')
            if not reporte_id:
                return JsonResponse({}, status=400)

            stop_event.set()
            if not deteccion_finalizada.wait(timeout=60):
                return JsonResponse({}, status=204)

            global resultado_final
            if resultado_final and "somnolencias" in resultado_final:
                reporte = Reporte.objects.get(pk=reporte_id)
                reporte.titulo = f"Digrafia, nivel {nivel}"
                reporte.puntaje = puntaje_real
                reporte.somnolencias = resultado_final.get("somnolencias", 0)
                reporte.distracciones = resultado_final.get("distracciones", 0)
                reporte.tiempos_somnolencia = resultado_final.get("tiempos_somnolencia", [])
                reporte.tiempos_distraccion = resultado_final.get("tiempos_distraccion", [])
                reporte.frames_somnolencia = resultado_final.get("frames_somnolencia", [])
                reporte.frames_distraccion = resultado_final.get("frames_distraccion", [])
                reporte.duracion_evaluacion = timedelta(seconds=tiempo)
                reporte.save()

                request.session[f"deteccion_iniciada_{nino_id}"] = False
                request.session.pop('reporte_id', None)
                request.session.modified = True

                resultado_final.clear()
                deteccion_finalizada.clear()

            return JsonResponse({}, status=204)

        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)



@method_decorator(csrf_exempt, name='dispatch')
class GuardarProgresoCartasView(View):
    def dispatch(self, request, *args, **kwargs):

NIÑO/templates/cartas.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <title>Juego de Cartas</title>
  <link rel="stylesheet" href="{% static 'CSS/cartas.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script>
    document.cookie = "csrftoken={{ csrf_token }}";
  </script>
</head>
<body>
  <!-- Botón de Pausa -->
  <button id="pausaBtn" class="button"> | | </button>

  <!-- Overlay y modal -->
  <div id="modalOverlay" class="modal-overlay"></div>
  <div class="container" id="modalPausa">
    <div class="input-field">
      <input type="button" value="Continuar" class="button-input" onclick="togglePausa()">
      <a class="button-input" href="{% url 'niño:cerrar_juego' %}">Salir</a>
    </div>
  </div>

  <!-- Estadísticas -->
  <div id="stats" class="oculto"></div>


  <!-- Contenedor del juego -->
  <div id="wrapper">
    <div id="game"></div>
  </div>
<audio id="musicaJuegos" loop autoplay>
    <source src="{% static 'musica/Niccolo Paganini -  La campanella (mp3cut.net).mp3' %}" type="audio/mpeg">
    Tu navegador no soporta audio HTML5.
  </audio>
  <script src="{% static 'JS/cartas.js' %}" defer></script>
</body>
</html>

NIÑO/templates/completar_palabra.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <title>Completa la Palabra</title>
  <link rel="stylesheet" href="{% static 'CSS/completar_palabra.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<script>
  document.cookie = "csrftoken={{ csrf_token }}";
</script>

<body>

  <button id="pausaBtn" class="button"> | | </button>


  <div id="modalOverlay" class="modal-overlay"></div>
  <div class="container" id="modalPausa">
    <div class="input-field">
      <input type="button" value="Continuar" class="button-input" onclick="togglePausa()">
      <a class="button-input" href="{% url 'niño:cerrar_juego' %}">Salir</a>
    </div>
  </div>


  <main class="contenido-juego">
    <h1>¡Completa la Palabra!</h1>


    <div class="cuadro-juego">
      <img id="imagenGuia" src="" alt="Guía visual" class="imagen-guia">
      <div class="palabra" id="contenedorPalabra"></div>
      <div id="contenedorLetras" class="letras-disponibles" ondrop="soltar(event)" ondragover="permitirSoltar(event)"></div>
      <button id="btnVerificar" onclick="verificarRespuesta()">Verificar</button>
    </div>
  </main>


  <div id="ventanaSiguienteNivel" class="ventana-nivel-oculta">
    <div class="contenedor-ventana">
      <button id="btnSiguienteNivel" class="btn-nivel" onclick="irSiguiente()">
        <span id="texto-btn-nivel">Siguiente palabra</span>
        <span class="flecha">➔</span>
      </button>
    </div>
  </div>


  <div id="mensaje-flotante"></div>


  <audio id="musicaJuegos" loop autoplay>
    <source src="{% static 'musica/castle (mp3cut.net).mp3' %}" type="audio/mpeg">
    Tu navegador no soporta audio HTML5.
  </audio>


  <script>
    const jsonUrl = "{% static 'json/niveles.json' %}?v={{ now|date:'U' }}";
    const urlNivelesDisgrafia = "{% url 'niño:niveles_disgrafia' %}";
    const guardarUrl = "{% url 'niño:guardar_progreso' %}";
  </script>


  <script src="{% static 'JS/completar_palabra.js' %}" defer></script>
</body>
</html>

NIÑO/templates/juego_multiplicaciones.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vamos a multiplicar</title>
    <link rel="stylesheet" href="{% static 'CSS/discalculiaStyles.css' %}">
</head>
<body>
    <div id="mensaje-flotante"></div>
    <!-- Botón de Pausa -->
    <button id="pausaBtn" class="button">⏸</button>

    <!-- Overlay y Modal de Pausa -->
    <div id="modalOverlay" class="modal-overlay"></div>
    <div class="container" id="modalPausa">
        <div class="input-field">
            <input type="button" value="Continuar" class="button-input" onclick="togglePausa()">
            <a class="button-input" href="{% url 'niño:cerrar_juego' %}">Salir</a>

        </div>
    </div>

    <!-- Overlay y Modal Final (REUTILIZANDO diseño de pausa) -->
    <div id="modalFinalOverlay" class="modal-overlay"></div>
    <div class="container" id="modalFinal" style="display: none;"></div>

    <!-- Fondo visual -->
    <div id="burbujas-container"></div>

    <!-- Contenedor principal del juego -->
    <div id="contenedor-juego">
        <h1>Vamos a Multiplicar</h1>
        <div id="contador-pregunta">Pregunta 1 de 15</div>
        <p id="pregunta"></p>

        <div id="opciones"></div>
        <p id="mensaje-resultado"></p>
    </div>

    <!-- Imágenes decorativas -->
    <img id="tiburon" src="{% static 'img/tiburon3.png' %}" alt="Tiburón">
    <img id="buzo" src="{% static 'img/buzo1.png' %}" alt="Buzo">


    <script>
        const buzo2URL = "{% static 'img/buzo2.png' %}";
        const buzo1URL = "{% static 'img/buzo1.png' %}";
    </script>

    <!-- Música de fondo -->
    <audio id="musicaJuegos" loop autoplay>
        <source src="{% static 'musica/nocturne in f.mp3' %}" type="audio/mpeg">
        Tu navegador no soporta audio HTML5.
    </audio>

    <!-- Script principal del juego -->
    <script src="{% static 'JS/juego_discalculia.js' %}"></script>
</body>
</html>

NIÑO/templates/juegos.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <title>Juegos Educativos</title>
  <link rel="stylesheet" href="{% static 'CSS/juegos_Styles.css' %}">
    <script src="{% static 'JS/juegos.js' %}" defer></script>

</head>
<body>
  <h1>¡Elige un juego y empieza a divertirte! </h1>

  <div class="game-card-wrapper">
       {% if juego == "Ordena las palabras" %}
      <a href="{% url 'niño:niveles_disgrafia' %}" class="game-card traza-y-gana-card">
        <span class="game-icon">
          <img src="{% static 'img/lapiz.png' %}" alt="lapiz" class="pencil-image-icon">
        </span>
        <span class="game-name">Ordena las palabras</span>
      </a>
     {% elif juego == "Cuenta conmigo" %}
      <a href="{% url 'niño:niveles_discalculia' %}" class="game-card cuenta-conmigo-card">
        <span class="game-numbers">
          <img src="{% static 'img/numero.png' %}" alt="numero" class="numero-image-icon">
        </span>
        <span class="game-name">Vamos a multiplicar</span>
      </a>
    {% elif juego == "Desafío de concentración" %}
           <a href="{% url 'niño:niveles_cartas' %}" class="game-card desafio-concentracion-card">
                 <span class="game-icon">
                <div class="traffic-light-body">
                    <img src="{% static 'img/semaforof.png' %}" alt="semaforo" class="semaforo-image-icon">
                </div>
                </span>
        <span class="game-name">Desafío de concentración</span>

                 </a>

    {% else %}
      <p>No se encontró un juego recomendado para esta discapacidad.</p>
    {% endif %}

  </div>
  <br />
  <a href="{% url 'niño:dashboardKid' %}" class="back-link">&#8592;</a>
     <!-- 🎵 Música del template de juegos -->
  <audio id="musicaJuegos" loop autoplay>
    <source src="{% static 'musica/musica_fondoparaentretiempos.mp3' %}" type="audio/mpeg">
    Tu navegador no soporta audio HTML5.
  </audio>

</body>
</html>

NIÑO/templates/niveles_cartas.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Selecciona un Nivel</title>
  <link rel="stylesheet" href="{% static 'CSS/juegos_Styles.css' %}">
    <script src="{% static 'JS/niveles_cartas.js' %}" defer></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
<!-- Mensaje flotante -->
<div id="mensaje-flotante"></div>


<h1 style="text-align: center;">¡QUE EMPIECE EL JUEGO!</h1>

<div class="grid-niveles-estatico">
  {% for i in "01234"|make_list %}
    {% with forloop.counter0 as numero_nivel %}
      {% if numero_nivel < nivel_desbloqueado %}
        <a href="{% url 'niño:juego_cartas' %}?nivel={{ numero_nivel }}" class="nivel-boton-estatico">Nivel {{ numero_nivel|add:1 }}</a>
      {% else %}
        <a href="#" class="nivel-boton-estatico bloqueado" onclick="mostrarMensajeFlotante('Debes completar el nivel anterior', 'orange')">Nivel {{ numero_nivel|add:1 }}</a>
      {% endif %}
    {% endwith %}
  {% endfor %}
</div>


<a href="{% url 'niño:juegos_recomendados' %}" class="back-link">&#8592;</a>
<audio id="musicaJuegos" loop autoplay>
    <source src="{% static 'musica/musicajuegosfondo (mp3cut.net).mp3' %}" type="audio/mpeg">
    Tu navegador no soporta audio HTML5.
  </audio>


</body>
</html>

NIÑO/templates/niveles_discalculia.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Selecciona un Nivel</title>
  <link rel="stylesheet" href="{% static 'CSS/juegos_Styles.css' %}">
    <script src="{% static 'JS/niveles_discalculia.js' %}" defer></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
<!-- Mensaje flotante -->
<div id="mensaje-flotante"></div>


<h1 style="text-align: center;">¡QUE EMPIECE EL JUEGO!</h1>

<div class="grid-niveles-estatico">
  {% for i in "01234"|make_list %}
    {% with forloop.counter0 as numero_nivel %}
      {% if numero_nivel < nivel_desbloqueado %}
        <a href="{% url 'niño:juego_multiplicacion' %}?nivel={{ numero_nivel }}" class="nivel-boton-estatico">Nivel {{ numero_nivel|add:1 }}</a>
      {% else %}
        <a href="#" class="nivel-boton-estatico bloqueado" onclick="mostrarMensajeFlotante('Debes completar el nivel anterior', 'orange')">Nivel {{ numero_nivel|add:1 }}</a>
      {% endif %}
    {% endwith %}
  {% endfor %}
</div>


<a href="{% url 'niño:juegos_recomendados' %}" class="back-link">&#8592;</a>
<audio id="musicaJuegos" loop autoplay>
    <source src="{% static 'musica/musicajuegosfondo (mp3cut.net).mp3' %}" type="audio/mpeg">
    Tu navegador no soporta audio HTML5.
  </audio>


</body>
</html>

NIÑO/templates/niveles_disgrafia.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Selecciona un Nivel</title>
  <link rel="stylesheet" href="{% static 'CSS/juegos_Styles.css' %}">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
<!-- Mensaje flotante -->
<div id="mensaje-flotante"></div>


<h1 style="text-align: center;">¡QUE EMPIECE EL JUEGO!</h1>

<div class="grid-niveles-estatico">
  {% for i in "01234"|make_list %}
    {% with forloop.counter0 as numero_nivel %}
      {% if numero_nivel < nivel_desbloqueado %}
        <a href="{% url 'niño:completar_palabra' %}?nivel={{ numero_nivel }}" class="nivel-boton-estatico">Nivel {{ numero_nivel|add:1 }}</a>
      {% else %}
        <a href="#" class="nivel-boton-estatico bloqueado" onclick="mostrarMensajeFlotante('Debes completar el nivel anterior', 'orange')">Nivel {{ numero_nivel|add:1 }}</a>
      {% endif %}
    {% endwith %}
  {% endfor %}
</div>


<a href="{% url 'niño:juegos_recomendados' %}" class="back-link">&#8592;</a>

<audio id="musicaJuegos" loop autoplay>
    <source src="{% static 'musica/musicajuegosfondo (mp3cut.net).mp3' %}" type="audio/mpeg">
    Tu navegador no soporta audio HTML5.
  </audio>
  <script src="{% static 'JS/niveles_disgrafia.js' %}"></script>

</body>
</html>