EDUFLEX/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
urlpatterns = [
    path('',include('accounts.urls',namespace='accounts')),
    path('',include('PADRE.urls',namespace='padre')),
    path('',include('PROFESOR.urls',namespace='profesor')),
    path('',include('NIÑO.urls',namespace='niño')),
    path('admin/', admin.site.urls)
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NIÑO/urls.py
from django.urls import path
from NIÑO.views import *

app_name = 'niño'

urlpatterns = [
    path('dashboardKid/', DashboardKid.as_view(), name='dashboardKid'),
    path('juegos_recomendados/', JuegosRecomendadosView.as_view(), name='juegos_recomendados'),
    path('niveles_disgrafia/', niveles_disgrafiaView.as_view(), name='niveles_disgrafia'),
    path('juego_completar/', juego_completar_palabraView.as_view(), name='completar_palabra'),
    path('guardar_progreso/', GuardarProgresoView.as_view(), name='guardar_progreso'),
    path('guardar_progreso_cartas/', GuardarProgresoCartasView.as_view(), name='guardar_progreso_cartas'),
    path('juego_cartas/', juego_cartasView.as_view(), name='juego_cartas'),
    path('niveles_cartas/', NivelesCartasView.as_view(), name='niveles_cartas'),
    path('preferencias/', PreferenciasUsuarioView.as_view(), name='preferencias'),
    path('editar-perfil/', EditarPerfilView.as_view(), name='editar_perfil'),
    path('guardar_progreso_multiplicacion/', GuardarProgresoMultiplicacionView.as_view(), name='guardar_progreso_multiplicacion'),
    path('juego_multiplicacion/', JuegoMultiplicacionView.as_view(), name='juego_multiplicacion'),
    path('niveles_discalculia/', NivelesDiscalculiaView.as_view(), name='niveles_discalculia'),
    path('cerrar_juego/', cerrar_juegoView.as_view(), name='cerrar_juego'),
]

accounts/urls.py
from django.urls import path
from accounts.views import *
app_name = 'accounts'
urlpatterns = [
path('',HomePageView.as_view(),name='home'),
path('login/',LoginView.as_view(),name='login'),
path('logout/',LogoutView.as_view(),name='logout'),
path('rol/',RolView.as_view(),name='rol'),
path('signupkid/',SignupKidView.as_view(),name='signupkid'),
path('signupdad/',SignupDadView.as_view(),name='signupdad'),
path('recuperar/<str:rol>/', EnviarCodigoView.as_view(), name='recover_password'),
path('verificar/', VerificarCodigoView.as_view(), name='verificar_codigo'),
path('cambiar/', CambiarContraseñaConCodigoView.as_view(), name='cambiar_contraseña')
]

accounts/models.py
from django.db import models
from django.utils import timezone
import datetime

class CodigoRecuperacion(models.Model):
    email = models.EmailField()
    codigo = models.CharField(max_length=6)
    creado_en = models.DateTimeField(auto_now_add=True)

    def expirado(self):
        return timezone.now() > self.creado_en + datetime.timedelta(minutes=10)

accounts/forms/login.py
from django import forms


class LoginPadreForm(forms.Form):
    usuario = forms.CharField(
        label='Usuario',
        max_length=30,
        widget=forms.TextInput(attrs={'placeholder': 'Usuario del padre'})
    )
    contraseña = forms.CharField(
        label='Contraseña',
        max_length=30,
        widget=forms.PasswordInput(attrs={'placeholder': 'Contraseña'})
    )

accounts/forms/recover_password.py
from django import forms
class SolicitarCodigoForm(forms.Form):
    email = forms.EmailField(label="Correo electrónico", widget=forms.EmailInput(attrs={
        'placeholder': 'Ingresa correo',
        'class': 'input',
    }))


class VerificarCodigoForm(forms.Form):
    codigo = forms.CharField(max_length=6, label="Código de verificación", widget=forms.TextInput(attrs={
        'placeholder': 'Ingresar código',
        'class': 'input',
    }))


class NuevaContraseñaForm(forms.Form):
    nueva = forms.CharField(label="Nueva contraseña", widget=forms.PasswordInput(attrs={
        'placeholder': 'Ingresar contraseña',
        'class': 'input',
    }))
    confirmar = forms.CharField(label="Confirmar contraseña", widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirmar contraseña',
        'class': 'input',
    }))

    def clean(self):
        cleaned = super().clean()
        if cleaned.get('nueva') != cleaned.get('confirmar'):
            raise forms.ValidationError("Las contraseñas no coinciden.")

accounts/forms/signupDad.py
import datetime
from EDUFLEX.utils import calcular_edad
from django import forms


from PADRE.models import Padre
class PadreForm(forms.ModelForm):
    confirmar_contraseña = forms.CharField(
        label="Confirmar Contraseña",
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirmar contraseña', 'id': 'confirmar_contraseña'})
    )

    class Meta:
        model = Padre
        fields = ['nombres', 'apellidos', 'genero', 'usuario', 'contraseña', 'fecha_nac', 'email',]

        widgets = {
            'nombres': forms.TextInput(attrs={'placeholder': 'Ingresar nombres', 'id': 'nombres'}),
            'apellidos': forms.TextInput(attrs={'placeholder': 'Ingresar apellidos', 'id': 'apellidos'}),
            'genero': forms.Select(attrs={'id': 'genero'}),
            'usuario': forms.TextInput(attrs={'placeholder': 'Ingresar usuario', 'id': 'usuario'}),
            'contraseña': forms.PasswordInput(attrs={'placeholder': 'Ingresar contraseña', 'id': 'contraseña'}),
            'fecha_nac': forms.DateInput(attrs={'type': 'date', 'id': 'fecha_nac'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Ingresar correo', 'id': 'email'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        contraseña = cleaned_data.get('contraseña')
        confirmar = cleaned_data.get('confirmar_contraseña')

        if contraseña and confirmar and contraseña != confirmar:
            self.add_error('confirmar_contraseña', 'Las contraseñas no coinciden.')

    def clean_fecha_nac(self):
        fecha = self.cleaned_data.get('fecha_nac')
        if fecha:
            if fecha > datetime.date.today():
                raise forms.ValidationError('La fecha de nacimiento no puede ser en el futuro.')

            edad = calcular_edad(fecha)
            if edad < 18:
                raise forms.ValidationError('La edad mínima es de 18 años.')

        return fecha

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if Padre.objects.filter(email=email).exists():
            raise forms.ValidationError("Este correo ya está registrado.")

        return email
    def clean_usuario(self):
        usuario = self.cleaned_data.get('usuario')
        if Padre.objects.filter(usuario=usuario).exists():
            raise forms.ValidationError("Este usario ya existe.")
        return usuario

    def clean_nombres(self):
        nombres = self.cleaned_data.get('nombres')
        if not nombres:
            raise forms.ValidationError("Este campo es obligatorio.")
        if not nombres.replace(' ', '').isalpha():
            raise forms.ValidationError("El nombre solo debe contener letras y espacios.")
        return nombres

    def clean_apellidos(self):
        apellidos = self.cleaned_data.get('apellidos')
        if not apellidos:
            raise forms.ValidationError("Este campo es obligatorio.")
        if not apellidos.replace(' ', '').isalpha():
            raise forms.ValidationError("El apellido solo debe contener letras y espacios.")
        return apellidos

accounts/views.py
from NIÑO.models import Niño
from PADRE.models import  Padre
from PROFESOR.models import Profesor
from accounts.forms.signupkid import NiñoForm
from accounts.forms.signupDad import PadreForm
from django.shortcuts import render, redirect
from django.views.generic import TemplateView,CreateView
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import View
from accounts.models import *
from accounts.forms.recover_password import *
from django.conf import settings
from django.core.mail import send_mail
from EDUFLEX.utils import *

class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)

class LoginView(TemplateView):
    template_name = 'login.html'
    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)

    def post(self, request):
        if 'usuario_padre' in request.POST:
            usuario = request.POST['usuario_padre']
            clave =cifrar_contraseña(request.POST['clave_padre'])

            try:
                padre = Padre.objects.get(usuario=usuario, contraseña=clave)
                request.session['padre_id'] = padre.id
                return redirect('padre:dashboardDad')
            except Padre.DoesNotExist:
                messages.error(request, "Credenciales incorrectas para padre.")
                return render(request, self.template_name)
        elif 'usuario_nino' in request.POST:
            usuario = request.POST['usuario_nino']
            clave = cifrar_contraseña(request.POST['clave_nino'])

            try:
                nino = Niño.objects.get(usuario=usuario, contraseña=clave)
                request.session['nino_id'] = nino.id
                return redirect('niño:dashboardKid')
            except Niño.DoesNotExist:
                messages.error(request, "Credenciales incorrectas para niño.")
                return render(request, self.template_name)
        elif 'usuario_profesor' in request.POST:
            usuario = request.POST['usuario_profesor']
            clave = cifrar_contraseña(request.POST['clave_profesor'])

            try:
                profesor = Profesor.objects.get(usuario=usuario, contraseña=clave)
                request.session['profesor_id'] = profesor.id
                return redirect('profesor:dashboardTeacher')
            except Profesor.DoesNotExist:
                messages.error(request, "Credenciales incorrectas para profesor.")
                return render(request, self.template_name)

        messages.error(request, "Formulario no válido.")
        return render(request, self.template_name)

class LogoutView(View):
    def get(self, request):
        request.session.flush()
        return redirect('accounts:login')

class RolView(TemplateView):
    template_name = 'rol.html'
    def get_context_data(self, **kwargs):
        context = super(RolView, self).get_context_data(**kwargs)

class SignupKidView(CreateView):
    model = Niño
    form_class = NiñoForm
    template_name = 'signupKid.html'
    success_url = reverse_lazy('accounts:login')

    def get_context_data(self, **kwargs):
        context = super(SignupKidView, self).get_context_data(**kwargs)
        return context
    def form_valid(self, form):
        contraseña_plana = form.cleaned_data['contraseña']
        contraseña_cifrada = hashlib.sha256(contraseña_plana.encode()).hexdigest()
        form.instance.contraseña = contraseña_cifrada
        form.instance.codigo = generar_codigo_unico()
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Error al crear la cuenta. Revisa los campos.")
        return self.render_to_response(self.get_context_data(form=form))

class SignupDadView(CreateView):
    model = Padre
    form_class = PadreForm
    template_name = 'signupDad.html'
    success_url = reverse_lazy('accounts:login')
    def get_context_data(self, **kwargs):
        context = super(SignupDadView, self).get_context_data(**kwargs)
        return  context

    def form_valid(self, form):

        contraseña_plana = form.cleaned_data['contraseña']
        contraseña_cifrada = hashlib.sha256(contraseña_plana.encode()).hexdigest()

        form.instance.contraseña = contraseña_cifrada

        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Error al crear la cuenta. Revisa los campos.")
        return self.render_to_response(self.get_context_data(form=form))




class EnviarCodigoView(View):
    template_name = 'recover_password.html'

    def get(self, request, rol):
        request.session['tipo_usuario'] = rol
        return render(request, self.template_name, {'form': SolicitarCodigoForm()})

    def post(self, request, rol):
        form = SolicitarCodigoForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data['email']
            tipo_usuario = rol.lower()
            usuario_obj = None

            if tipo_usuario == 'padre':
                print('→ Solicitud de padre')
                if Padre.objects.filter(email=email).exists():
                    usuario_obj = Padre.objects.get(email=email)
                else:
                    messages.error(request, "No hay un padre con ese correo.")
                    return render(request, self.template_name, {'form': form})

            elif tipo_usuario == 'niño':
                if Niño.objects.filter(email=email).exists():
                    usuario_obj = Niño.objects.get(email=email)
                else:
                    messages.error(request, "No hay un niño con ese correo.")
                    return render(request, self.template_name, {'form': form})
            else:
                messages.error(request, "Tipo de usuario inválido.")
                return render(request, self.template_name, {'form': form})


            request.session['recuperacion_email'] = email
            request.session['tipo_usuario'] = tipo_usuario


            codigo = str(random.randint(100000, 999999))
            CodigoRecuperacion.objects.create(email=email, codigo=codigo)

            # Enviar el correo con el remitente verificado
            try:
                send_mail(
                    'Código de recuperación - Eduflex',
                    f'Tu código es: {codigo}',
                    settings.DEFAULT_FROM_EMAIL,
                    [email],
                    fail_silently=False,
                )

            except Exception as e:

                messages.error(request, f"Error al enviar el correo: {e}")
                return render(request, self.template_name, {'form': form})

            messages.success(request, "Código enviado a tu correo.")
            return redirect('accounts:verificar_codigo')

        return render(request, self.template_name, {'form': form})


class VerificarCodigoView(View):
    template_name = 'validate_code.html'

    def get(self, request):
        return render(request, self.template_name, {'form': VerificarCodigoForm()})

    def post(self, request):
        form = VerificarCodigoForm(request.POST)
        email = request.session.get('recuperacion_email')

        if form.is_valid() and email:
            codigo = form.cleaned_data['codigo']
            codigos = CodigoRecuperacion.objects.filter(email=email, codigo=codigo).order_by('-creado_en')

            if codigos and not codigos[0].expirado():
                request.session['codigo_validado'] = True
                return redirect('accounts:cambiar_contraseña')
            else:
                messages.error(request, "Código inválido o expirado.")

        return render(request, self.template_name, {'form': form})



class CambiarContraseñaConCodigoView(View):
    template_name = 'new_password.html'

    def get(self, request):
        if not request.session.get('codigo_validado'):
            return redirect('accounts:verificar_codigo')
        return render(request, self.template_name, {'form': NuevaContraseñaForm()})

    def post(self, request):
        form = NuevaContraseñaForm(request.POST)
        email = request.session.get('recuperacion_email')
        tipo = request.session.get('tipo_usuario')

        if form.is_valid() and email and tipo:
            nueva = cifrar_contraseña(form.cleaned_data['nueva'])

            try:
                if tipo == 'padre':
                    usuario = Padre.objects.get(email=email)
                elif tipo == 'niño':
                    usuario = Niño.objects.get(email=email)
                else:
                    raise ValueError("Tipo de usuario inválido")

                usuario.contraseña = nueva
                usuario.save()
                request.session.flush()
                return redirect('accounts:login')

            except (Padre.DoesNotExist, Niño.DoesNotExist):
                messages.error(request, "No se encontró el usuario.")

        return render(request, self.template_name, {'form': form})

accounts/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>EDUFLEX</title>
</head>
<body>

</body>
</html><!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Eduflex - Aprende Jugando</title>
    <link rel="stylesheet" href="{% static 'CSS/home.css' %}" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>

  <div class="header">
    <div class="logo">
      <img src="{% static 'img/logo.png' %}" alt="Logo Eduflex" width="70">
    </div>
    <div class="buttons">
      <a href="{% url 'accounts:login' %}" class="boton-login">Iniciar sesión</a>
      <a href="{% url 'accounts:rol' %}" class="boton-registrar">Registrar</a>

    </div>
  </div>

  <div class="main">
    <h1>Aprende Jugando</h1>
    <p>Bienvenido! Este es tu espacio para aprender y divertirte cada día.</p>
  </div>

  <div class="features">
    <div class="card descubre">
      <h3>Descubre</h3>
      <p>Explora actividades diseñadas para aprender jugando. Colores, sonidos, formas y más, ¡todo a tu ritmo!</p>
    </div>
    <div class="card desarrolla">
      <h3>Desarrolla</h3>
      <p>Mejora habilidades con tareas sencillas y divertidas. Pensamiento lógico, creatividad y memoria. ¡Todo a tu ritmo!</p>
    </div>
    <div class="card acompaña">
      <h3>Acompaña</h3>
      <p>Esta app está pensada para niños con necesidades especiales. Ofrece apoyo visual, auditivo y guía paso a paso.</p>
    </div>
  </div>

</body>
</html>

accounts/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Iniciar Sesión - Eduflex</title>
  <link rel="stylesheet" href="{% static 'CSS/login.css' %}" />
  <script src="{% static 'js/login.js' %}"></script>
</head>
<body>

  <div class="logo">
    <img src="{% static 'img/logo.png' %}" alt="Logo Eduflex">
  </div>

  <div class="container">
    <div class="regresar">
      <a href="{% url 'accounts:home' %}" class="boton-recuperar">←</a>
    </div>

    <h2>INICIAR SESIÓN</h2>


    <div class="role-buttons">
      <button type="button" onclick="mostrarFormulario('padre')">Padre</button>
      <button type="button" onclick="mostrarFormulario('nino')">Niño</button>
      <button type="button" onclick="mostrarFormulario('profesor')">Profesor</button>
    </div>


    <form id="form-padre" class="form-role active" method="post">
      {% csrf_token %}
       {% if messages %}
           <ul class="messages errorlist">
             {% for message in messages %}
               <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
             {% endfor %}
           </ul>
        {% endif %}
      <input type="text" id="usuario_padre" name="usuario_padre" placeholder="Usuario del padre" required />
      <input type="password" id="clave_padre" name="clave_padre" placeholder="Contraseña" required />

      <div class="crear-cuenta">
        <a href="{% url 'accounts:rol' %}" class="boton-crear">Crear cuenta</a>
        <button type="submit" class="btn-ingresar">INGRESAR</button>
      </div>

      <div class="forgot-password">
        <a href="{% url 'accounts:recover_password' 'padre' %}" class="boton-recuperar">¿Has olvidado tu contraseña?</a>
      </div>
    </form>


    <form id="form-nino" class="form-role" method="post">
      {% csrf_token %}
         {% if messages %}
           <ul class="messages errorlist">
             {% for message in messages %}
               <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
             {% endfor %}
           </ul>
        {% endif %}
      <input type="text" id="usuario_nino" name="usuario_nino" placeholder="Usuario del niño" required />
      <input type="password" id="clave_nino" name="clave_nino" placeholder="Contraseña" required />

      <div class="crear-cuenta">
        <a href="{% url 'accounts:rol' %}" class="boton-crear">Crear cuenta</a>
        <button type="submit" class="btn-ingresar">INGRESAR</button>
      </div>

      <div class="forgot-password">
        <a href="{% url 'accounts:recover_password' 'niño' %}" class="boton-recuperar">¿Has olvidado tu contraseña?</a>
      </div>
    </form>
    <form id="form-profesor" class="form-role" method="post">
      {% csrf_token %}
       {% if messages %}
           <div class="messages errorlist">
             {% for message in messages %}
               <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
             {% endfor %}
           </div>
       {% endif %}
      <input type="text" id="usuario_profesor" name="usuario_profesor" placeholder="Usuario del profesor" required />
      <input type="password" id="clave_profesor" name="clave_profesor" placeholder="Contraseña" required />

      <div class="crear-cuenta">
        <a href="{% url 'accounts:rol' %}" class="boton-crear">Crear cuenta</a>
        <button type="submit" class="btn-ingresar">INGRESAR</button>
      </div>
    </form>
  </div>

<script>
  setTimeout(() => {
    document.querySelectorAll('.errorlist').forEach(el => {
      el.classList.add('fade-out');
      setTimeout(() => el.style.display = 'none', 600);
    });
  }, 3000);
</script>

</body>
</html>

accounts/templates/new_password.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Establecer nueva contraseña</title>
  <link rel="stylesheet" href="{% static 'CSS/recuperacion.css' %}">
</head>
<body>
  <div class="recuperacion-container">
    <div class="left-panel">
      <img src="{% static 'img/logo.png' %}" alt="Logo Eduflex" class="logo">
    </div>
    <div class="right-panel">
      <div class="form-box">
        <a href="{% url 'accounts:login' %}" class="back-arrow">←</a>
        <h2>Recuperar contraseña</h2>
        <p>Ingresa tu nueva contraseña. Asegúrate de que sea segura y fácil de recordar.</p>

        {% if messages %}
          <ul class="messages">
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}

        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn">Cambiar contraseña</button>
        </form>
      </div>
    </div>
  </div>
</body>
</html>

accounts/templates/rol.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Elige tu rol</title>
  <link rel="stylesheet" href="{% static 'CSS/rol.css' %}">
</head>
<body>

  <div class="card">
    <div class="regresar">
        <a href="{% url 'accounts:login' %}" class="boton-recuperar">←</a>
    </div>
    <h2>Elige tu rol</h2>
    <div class="roles">
      <div class="role"  onclick="window.location.href='{% url 'accounts:signupkid' %}'">
        <div>🧒</div>
        <h3>NIÑO</h3>
        <p>Juega, aprende y desbloquea premios mientras te diviertes.</p>
      </div>
      <div class="role" onclick="window.location.href='{% url 'accounts:signupdad' %}'">
        <div>👨‍👩‍👦</div>
        <h3>PADRE</h3>
        <p>Monitorea el progreso, establece metas y ajusta el contenido para tu hijo.</p>
      </div>

    </div>
  </div>

</body>
</html>

accounts/templates/signupDad.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Crear Cuenta - Eduflex</title>
  <link rel="stylesheet" href="{% static 'css/signup.css' %}">
</head>
{% block content %}
<body>
  <div class="logo">
    <img src="{% static 'img/logo.png' %}" alt="Logo Eduflex">
  </div>

  <form method="post" class="container">
    {% csrf_token %}

    <div class="regresar">
      <a href="{% url 'accounts:rol' %}" class="boton-recuperar">←</a>
    </div>

    <h2>CREAR CUENTA</h2>

    <div class="field">
      {{ form.nombres.label_tag }}
      {{ form.nombres }}
      {{ form.nombres.errors }}

    </div>

    <div class="field">
      {{ form.email.label_tag }}
      {{ form.email }}
      {{ form.email.errors }}
    </div>

    <div class="field">
      {{ form.apellidos.label_tag }}
      {{ form.apellidos }}
      {{ form.apellidos.errors }}
    </div>
      <div class="field">
          {{ form.fecha_nac.label_tag }}
          {{ form.fecha_nac }}
          {{ form.fecha_nac.errors }}

      </div>

      <div class="field">
          {{ form.usuario.label_tag }}
          {{ form.usuario }}
          {{ form.usuario.errors }}
      </div>

      <div class="field">
          {{ form.genero.label_tag }}
          {{ form.genero }}
      </div>

      <div class="field">
          {{ form.contraseña.label }}
          {{ form.contraseña }}
          {{ forml.contraseña.errors }}
          {{ form.confirmar_contraseña.label_tag }}
          {{ form.confirmar_contraseña }}
          {{ form.confirmar_contraseña.errors }}
      </div>

      <div class="full-width">
          <button type="submit" class="btn">Crear</button>
      </div>
  </form>
</body>
{% endblock %}
<script>
  setTimeout(() => {
    document.querySelectorAll('.errorlist').forEach(el => {
      el.classList.add('fade-out');
      setTimeout(() => el.style.display = 'none', 600);
    });
  }, 4000);
</script>
</html>

accounts/templates/signupKid.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Crear Cuenta - Eduflex</title>
  <link rel="stylesheet" href="{% static 'css/signup.css' %}">
</head>
{% block content %}
<body>
  <div class="logo">
    <img src="{% static 'img/logo.png' %}" alt="Logo Eduflex">
  </div>

  <form method="post" class="container" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="regresar">
      <a href="{% url 'accounts:rol' %}" class="boton-recuperar">←</a>
    </div>

    <h2>CREAR CUENTA</h2>

    <div class="field">
      {{ form.nombres.label_tag }}
      {{ form.nombres }}
      {{ form.nombres.errors }}
    </div>

    <div class="field">
      {{ form.email.label_tag }}
      {{ form.email }}
      {{ form.email.errors }}
    </div>

    <div class="field">
      {{ form.apellidos.label_tag }}
      {{ form.apellidos }}
      {{ form.apellidos.errors }}
    </div>
 
    <div class="field">
      {{ form.especialidad.label_tag }}
      {{ form.especialidad }}
    </div>

    <div class="field">
      {{ form.fecha_nac.label_tag }}
      {{ form.fecha_nac }}
      {{ form.fecha_nac.errors }}
    </div>



    <div class="field">
      {{ form.genero.label_tag }}
      {{ form.genero }}
    </div>


    <div class="field">
      {{ form.contraseña.label }}
      {{ form.contraseña }}
      {{ form.contraseña.errors }}
    </div>

    <div class="field">
      {{ form.usuario.label_tag }}
      {{ form.usuario }}
      {{ form.usuario.errors }}
    </div>
      
    <div class="field">
      {{ form.confirmar_contraseña.label_tag }}
      {{ form.confirmar_contraseña }}
      {{ form.confirmar_contraseña.errors }}
    </div>


    <div class="field">
      {{ form.foto_perfil.label_tag }}
      {{ form.foto_perfil }}
      {{ form.foto_perfil.errors }}
    </div>
    <div class="full-width">
      <button type="submit" class="btn">Crear</button>
    </div>
  </form>
</body>
{% endblock %}
<script>
  setTimeout(() => {
    document.querySelectorAll('.errorlist').forEach(el => {
      el.classList.add('fade-out');
      setTimeout(() => el.style.display = 'none', 600);
    });
  }, 4000);
</script>
</html>