EDUFLEX/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
urlpatterns = [
    path('',include('accounts.urls',namespace='accounts')),
    path('',include('PADRE.urls',namespace='padre')),
    path('',include('PROFESOR.urls',namespace='profesor')),
    path('',include('NIÑO.urls',namespace='niño')),
    path('admin/', admin.site.urls)
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NIÑO/urls.py
from django.urls import path
from NIÑO.views import *

app_name = 'niño'

urlpatterns = [
    path('dashboardKid/', DashboardKid.as_view(), name='dashboardKid'),
    path('juegos_recomendados/', JuegosRecomendadosView.as_view(), name='juegos_recomendados'),
    path('niveles_disgrafia/', niveles_disgrafiaView.as_view(), name='niveles_disgrafia'),
    path('juego_completar/', juego_completar_palabraView.as_view(), name='completar_palabra'),
    path('guardar_progreso/', GuardarProgresoView.as_view(), name='guardar_progreso'),
    path('guardar_progreso_cartas/', GuardarProgresoCartasView.as_view(), name='guardar_progreso_cartas'),
    path('juego_cartas/', juego_cartasView.as_view(), name='juego_cartas'),
    path('niveles_cartas/', NivelesCartasView.as_view(), name='niveles_cartas'),
    path('preferencias/', PreferenciasUsuarioView.as_view(), name='preferencias'),
    path('editar-perfil/', EditarPerfilView.as_view(), name='editar_perfil'),
    path('guardar_progreso_multiplicacion/', GuardarProgresoMultiplicacionView.as_view(), name='guardar_progreso_multiplicacion'),
    path('juego_multiplicacion/', JuegoMultiplicacionView.as_view(), name='juego_multiplicacion'),
    path('niveles_discalculia/', NivelesDiscalculiaView.as_view(), name='niveles_discalculia'),
    path('cerrar_juego/', cerrar_juegoView.as_view(), name='cerrar_juego'),
]

PROFESOR/urls.py
from django.urls import path
from PROFESOR.views import *
app_name = 'profesor'
urlpatterns = [
    path('dashboardTeacher/',DashboardTeacher.as_view(),name='dashboardTeacher'),
    path('tuscursos/',CursoTeacher.as_view(),name='tuscursos'),
    path('curso/<int:curso_id>/',PresentarCursoTeacher.as_view(),name='curso'),
    path('estudiante/<int:curso_id>/<int:niño_id>', reportEstudiante.as_view(), name='estudiante'),
    path('verReportStudent/<int:reporte_id>/<int:curso_id>', verReportStudent.as_view(), name='verReportStudent'),
    path('statsKid/<int:niño_id>/<int:curso_id>/', Estadisticas_niño.as_view(),name='verEstadisticasNiño'),
    path('statsCourse/<int:curso_id>/',Estadisticas_curso.as_view(), name='verEstadisticasCurso'),
    path('guardar_comentario/', GuardarComentarios.as_view(), name='guardar_comentario'),
]

accounts/urls.py
from django.urls import path
from accounts.views import *
app_name = 'accounts'
urlpatterns = [
path('',HomePageView.as_view(),name='home'),
path('login/',LoginView.as_view(),name='login'),
path('logout/',LogoutView.as_view(),name='logout'),
path('rol/',RolView.as_view(),name='rol'),
path('signupkid/',SignupKidView.as_view(),name='signupkid'),
path('signupdad/',SignupDadView.as_view(),name='signupdad'),
path('recuperar/<str:rol>/', EnviarCodigoView.as_view(), name='recover_password'),
path('verificar/', VerificarCodigoView.as_view(), name='verificar_codigo'),
path('cambiar/', CambiarContraseñaConCodigoView.as_view(), name='cambiar_contraseña')
]

PROFESOR/models.py
from django.db import models
from NIÑO.models import *
Jornadas_CHOICES=[('M','Matutina'),('V','Vespertina')]
SEX_CHOICES=[('M', 'Masculino'), ('F', 'Femenino')]
ESPECIALIDAD=[('P','psicopedagogo'),('T','Trastornos de la escritura'),('N','neuroeducación aplicada al TDAH')]
class Profesor(models.Model):
    nombres=models.CharField(max_length=100)
    apellidos=models.CharField(max_length=100)
    genero=models.CharField(max_length=1,choices=SEX_CHOICES)
    usuario=models.CharField(max_length=30)
    contraseña = models.CharField(max_length=64)
    fecha_nac=models.DateField()
    email=models.EmailField()
    especializacion = models.CharField(max_length=1,choices=ESPECIALIDAD)
    @property
    def nombre_completo(self):
        return f"{self.nombres} {self.apellidos}"
    def __str__(self):
        return f"{self.nombres} {self.apellidos}"

class Curso(models.Model):
    profesor=models.ForeignKey(Profesor,on_delete=models.CASCADE ,null=True)
    nombre_curso=models.CharField(max_length=100)
    seccion=models.CharField(max_length=1,choices=Jornadas_CHOICES)
    descripcion=models.CharField(max_length=100)
    niños = models.ManyToManyField(Niño, related_name='cursos')
    periodo=models.CharField(max_length=9 , null=True, blank=True)
    fecha_inicio=models.DateField(null=True, blank=True)
    fecha_final=models.DateField(null=True, blank=True)
    def __str__(self):
        return f"{self.nombre_curso} - {self.get_seccion_display()}"

    def mostrar_seccion(self):
        return dict(Jornadas_CHOICES).get(self.seccion, "Sin definir")

PROFESOR/forms/curso.py
from django import forms
from PROFESOR.models import Curso

class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = ['nombre_curso', 'seccion', 'descripcion','periodo']
        widgets = {
            'nombre_curso': forms.TextInput(attrs={'placeholder': 'Ej.2B','id':'nombre_curso'}),
            'seccion': forms.Select(attrs={'placeholder': 'Ej. Matutina','id':'seccion'}),
            'descripcion': forms.Textarea(attrs={'placeholder': 'Descripción breve','id':'descripcion', 'rows': 3}),
            'periodo': forms.TextInput(attrs={'placeholder': 'ej. 2025-2026','id':'periodo'}),
        }

PROFESOR/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views import View
from django.views.generic import TemplateView,ListView
from django.db.models import Q
from PROFESOR.models import  Profesor,Curso
from NIÑO.models import  Reporte,Niño
import  os,statistics,operator
from functools import reduce
from datetime import timedelta
from django.conf import settings
class DashboardTeacher(TemplateView):
    template_name = 'dashboardTeacher.html'

    def dispatch(self, request, *args, **kwargs):
        if 'profesor_id' not in request.session:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profesor_id = self.request.session.get('profesor_id')
        profesor = get_object_or_404(Profesor, id=profesor_id)
        cursos=Curso.objects.filter(profesor=profesor_id)
        context['cursos'] = cursos
        context['profesor'] = profesor
        return context

class CursoTeacher(TemplateView):
    template_name = 'tus_cursos.html'

    def dispatch(self, request, *args, **kwargs):
        if 'profesor_id' not in request.session:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profesor_id = self.request.session.get('profesor_id')
        curso_profesor=Curso.objects.filter(profesor=profesor_id)
        context['cursos'] = curso_profesor
        return context

class PresentarCursoTeacher(ListView):
    template_name = 'curso_estudiante.html'
    context_object_name = 'niños'
    pk_url_kwarg = 'curso_id'

    def dispatch(self, request, *args, **kwargs):
        if 'profesor_id' not in request.session:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        pk = self.kwargs.get(self.pk_url_kwarg)
        curso = get_object_or_404(Curso, pk=pk)
        queryset = curso.niños.all()

        nombre = self.request.GET.get('nombre', '').strip()
        genero = self.request.GET.get('genero')

        if nombre:
            palabras = nombre.split()
            queries = [
                Q(nombres__icontains=palabra) | Q(apellidos__icontains=palabra)
                for palabra in palabras
            ]
            queryset = queryset.filter(reduce(operator.and_, queries))
        if genero:
            queryset = queryset.filter(genero=genero)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        curso = get_object_or_404(Curso, pk=self.kwargs.get(self.pk_url_kwarg))
        context['curso'] = curso
        context['nombre'] = self.request.GET.get('nombre', '')
        context['genero'] = self.request.GET.get('genero', '')
        return context

class reportEstudiante(TemplateView):
    template_name = 'reporte_niño.html'
    def dispatch(self, request, *args, **kwargs):
        if 'profesor_id' not in request.session:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        niño_id = self.kwargs.get('niño_id')
        curso_id = self.kwargs.get('curso_id')
        curso=Curso.objects.get(pk=curso_id)
        nino = Niño.objects.get(pk=niño_id)
        context['nino'] = nino
        context['curso'] = curso
        context['reportes'] = Reporte.objects.filter(niño=nino,fecha__range=(curso.fecha_inicio, curso.fecha_final)).order_by('-fecha')
        return context


class verReportStudent(TemplateView):
        template_name = 'verReportStudent.html'
        def dispatch(self, request, *args, **kwargs):
            if 'profesor_id' not in request.session:
                return redirect('accounts:login')
            return super().dispatch(request, *args, **kwargs)
        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            reporte_id = self.kwargs.get('reporte_id')
            reporte = Reporte.objects.get(pk=reporte_id)
            nino_id = reporte.niño.id
            nino= Niño.objects.get(pk=nino_id)
            curso_id = self.kwargs.get('curso_id')
            curso= Curso.objects.get(pk=curso_id)
            base_dir = os.path.join('capturas', str(nino_id), str(reporte_id))
            media_dir = os.path.join(settings.MEDIA_ROOT, base_dir)

            frames_somnolencia = []
            frames_distraccion = []

            if os.path.exists(media_dir):
                for nombre in os.listdir(media_dir):
                    if nombre.startswith('somnolencia'):
                        frames_somnolencia.append(f"{base_dir}/{nombre}")
                    elif nombre.startswith('distraccion'):
                        frames_distraccion.append(f"{base_dir}/{nombre}")

            pares_somnolencia = zip(frames_somnolencia, reporte.tiempos_somnolencia or [])
            pares_distraccion = zip(frames_distraccion, reporte.tiempos_distraccion or [])
            promedio_somnolencia = round(statistics.mean(reporte.tiempos_somnolencia),
                                         2) if reporte.tiempos_somnolencia else 0
            promedio_distraccion = round(statistics.mean(reporte.tiempos_distraccion),
                                         2) if reporte.tiempos_distraccion else 0
            total_somnolencia = sum(reporte.tiempos_somnolencia or [])
            total_distraccion = sum(reporte.tiempos_distraccion or [])
            tiempo_concentracion = (
                    reporte.duracion_evaluacion
                    - timedelta(seconds=total_somnolencia)
                    - timedelta(seconds=total_distraccion)
            )
            context['nino'] = nino
            context['curso']=curso
            context['reporte'] = reporte
            context['puntaje']= round((reporte.puntaje or 0) / 10, 2)
            context['pares_somnolencia'] = list(pares_somnolencia)
            context['pares_distraccion'] = list(pares_distraccion)
            context['promedio_somnolencia'] = promedio_somnolencia
            context['promedio_distraccion'] = promedio_distraccion
            context['total_somnolencia'] = total_somnolencia
            context['total_distraccion'] = total_distraccion
            context['tiempo_concentracion'] = tiempo_concentracion
            context['grafico_data'] = {
                'distracciones': reporte.distracciones or 0,
                'somnolencias': reporte.somnolencias or 0,
                'tiempos_somnolencia': reporte.tiempos_somnolencia or [],
                'tiempos_distraccion': reporte.tiempos_distraccion or [],
            }

            return context


class Estadisticas_niño(TemplateView):
    template_name = "estadisticas_generales_niño.html"
    def dispatch(self, request, *args, **kwargs):
        if 'profesor_id' not in request.session:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        niño_id = self.kwargs.get('niño_id')
        curso_id = self.kwargs.get('curso_id')
        nino = get_object_or_404(Niño, pk=niño_id)
        reportes = Reporte.objects.filter(niño=nino)
        curso=get_object_or_404(Curso, pk=curso_id)
        nivel = self.request.GET.get('nivel')
        fecha_i = self.request.GET.get('fecha_i')
        fecha_f = self.request.GET.get('fecha_f')

        if nivel:
            reportes = reportes.filter(titulo__icontains=f'nivel {nivel}')
        if fecha_i and fecha_f:
            reportes = reportes.filter(fecha__range=[fecha_i, fecha_f])
        elif fecha_i:
            reportes = reportes.filter(fecha__gte=fecha_i)
        elif fecha_f:
            reportes = reportes.filter(fecha__lte=fecha_f)

        total_distracciones = sum(r.distracciones or 0 for r in reportes)
        total_somnolencias = sum(r.somnolencias or 0 for r in reportes)
        cantidad_reportes = reportes.count()
        puntajes = [
            {
                'fecha': r.fecha.strftime('%Y-%m-%d'),
                'puntaje': round(float(r.puntaje) / 10, 2) if r.puntaje is not None else 0
            }
            for r in reportes
        ]
        distracciones = [
            {
                'fecha': r.fecha.strftime('%Y-%m-%d'),
                'distracciones': int(r.distracciones) if r.distracciones is not None else 0
            }
            for r in reportes
        ]
        somnolencias = [
            {
                'fecha': r.fecha.strftime('%Y-%m-%d'),
                'somnolencias': int(r.somnolencias) if r.somnolencias is not None else 0
            }
            for r in reportes
        ]
        tiempos_distraccion_sumados = [
            {
                'fecha': r.fecha.strftime('%Y-%m-%d'),
                'tiempo_total_distraccion': float(sum(r.tiempos_distraccion or []))
            }
            for r in reportes
        ]
        tiempos_somnolencia_sumados = [
            {
                'fecha': r.fecha.strftime('%Y-%m-%d'),
                'tiempo_total_somnolencia': float(sum(r.tiempos_somnolencia or []))
            }
            for r in reportes
        ]
        tiempos = [r['tiempo_total_distraccion'] for r in tiempos_distraccion_sumados]
        promedio_tiempo_distraccion = round(statistics.mean(tiempos), 2) if tiempos else 0
        tiempos_som = [r['tiempo_total_somnolencia'] for r in tiempos_somnolencia_sumados]
        promedio_tiempo_somnolencia = round(statistics.mean(tiempos_som), 2) if tiempos_som else 0
        solo_puntajes = [p['puntaje'] for p in puntajes]
        promedio_puntaje = round(statistics.mean(solo_puntajes), 2) if solo_puntajes else 0

PROFESOR/templates/curso_estudiante.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Lista de Estudiantes</title>
    <link rel="stylesheet" href="{% static 'css/estudiantes.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;600&display=swap" rel="stylesheet">
</head>
<body>

<header>
    <div class="logo">
        <img src="{% static 'img/logo.png' %}" alt="Eduflex">
        <a href="{% url 'profesor:verEstadisticasCurso' curso.id %}" class="btn">Estadísticas generales curso</a>
    </div>
</header>

<div class="regresar">
    <a class="boton-recuperar" href="{% url 'profesor:tuscursos'%}"> ← Regresar</a>
</div>


<form method="get">
    <div class="filtros">
        <input type="text" id="filtro-nombre" name="nombre" value="{{ nombre }}" placeholder="Buscar por nombre...">
        <select id="filtro-genero" name="genero">
            <option value="" {% if genero == "" %}selected{% endif %}>Todos los géneros</option>
            <option value="M" {% if genero == "M" %}selected{% endif %}>Masculino</option>
            <option value="F" {% if genero == "F" %}selected{% endif %}>Femenino</option>
        </select>
        <button type="submit">Filtrar</button>
    </div>
</form>



<div class="container">
    <h1>Estudiantes del Curso</h1>

    <ul class="lista-estudiantes">
        {% for niño in niños %}
            <li class="item-estudiante"
                data-nombre="{{ niño.nombres }} {{ niño.apellidos }}"
                data-genero="{{ niño.genero }}">
                <a href="{% url 'profesor:estudiante' curso.id niño.id %}">
                    {% if niño.foto_perfil %}
                        <img src="{{ niño.get_image }}" class="imagen-niño">
                    {% endif %}
                    <span class="nombre">📘 {{ niño.nombres }} {{ niño.apellidos }}</span>
                    <span class="ver-mas">Ver detalle ➜</span>
                </a>
            </li>
        {% empty %}
            <li class="sin-estudiantes">No hay estudiantes registrados.</li>
        {% endfor %}
    </ul>
</div>

<!-- Modal para imagen -->
<div id="modal-imagen" class="modal">
    <span class="cerrar" id="cerrar-modal">&times;</span>
    <img class="modal-contenido" id="img-modal">
</div>


<script>
document.querySelectorAll('.imagen-niño').forEach(img => {
    img.style.cursor = "pointer";
    img.addEventListener('click', function(event) {
        event.preventDefault(); // Evita navegación si la imagen está dentro de un enlace
        document.getElementById('modal-imagen').style.display = "block";
        document.getElementById('img-modal').src = this.src;
    });
});

document.getElementById('cerrar-modal').onclick = function() {
    document.getElementById('modal-imagen').style.display = "none";
};

document.getElementById('modal-imagen').onclick = function(event) {
    // Solo cierra si el clic es fuera de la imagen modal y fuera de la "X"
    if (event.target === this) {
        this.style.display = "none";
    }
};
</script>


</body>
</html>

PROFESOR/templates/dashboardTeacher.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Dashboard Profesor - Eduflex</title>
    <link rel="stylesheet" href="{% static 'css/dashboardTeacher.css' %}">
</head>
<body>
    <header>
        <div class="logo">
            <img src="{% static 'img/logo.png' %}" alt="Eduflex">
            <a href="{% url 'profesor:tuscursos' %}" class="btn">Cursos</a>
        </div>
        <nav>

            <a href="{% url 'accounts:logout' %}" class="btn-cerrar">Cerrar sesión</a>
        </nav>
    </header>

    <main>
        <div class="container">
        <div class="welcome">
          ¡Bienvenido/a, {{profesor.nombre_completo}}!<br>
          Accede a tus cursos y al seguimiento de tus estudiantes.
        </div>

        <div class="content">
          <div class="progress-courses {% if not cursos %}sin-reportes{% endif %}">
              <div class="progress-title">Cursos visitados recientemente</div>
              {% if cursos%}
              {% for curso in cursos %}
                <a class="card-container" href="{% url 'profesor:curso' curso.id %}" >
                  <div class="card">
                    <div><strong>{{ curso.nombre_curso}}</strong></div>
                      <div>
                          {% if curso.seccion == "M" %}
                            Matutina
                          {% elif curso.seccion == "V" %}
                            Vespertina
                          {% else %}
                            {{ curso.seccion }}
                          {% endif %}
                      </div>
                      <div>Periodo: {{ curso.periodo }}</div>
                      <div>Fecha inicio: {{ curso.fecha_inicio|date:"M d, Y" }}</div>
                      <div>Fecha fin: {{ curso.fecha_final|date:"M d, Y" }}</div>
                  </div>
                </a>
              {% endfor %}

              {% else %}
                    <p>No tienes cursos disponibles</p>
              {% endif %}
          </div>
          <div class="imagen-con-circulo">
              <div class="circulo-beis"></div>
              <img src="{% static 'img/profesor.png' %}" class alt="Ilustración profesora">
          </div>
        </div>
      </div>
    </main>
</body>
</html>

PROFESOR/templates/estadisticas_generales_curso.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Estadísticas Generales</title>
  <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'CSS/estadisticasGeneralesPadre.css' %}">
  <script src="{% static 'js/graficas_reportes.js' %}"></script>
  <script src="https://d3js.org/d3.v7.min.js"></script>
</head>
<body>

<header>
  <div class="logo">
    <img src="{% static 'img/logo.png' %}" alt="Eduflex Logo">
    <a href="{% url 'profesor:dashboardTeacher' %}" class="btn-nav">🏠 Home</a>
  </div>
  <a href="{% url 'accounts:logout' %}" class="btn-cerrar">Cerrar sesión</a>
</header>

<div class="regresar">
  <a class="boton-recuperar" href="{% url 'profesor:curso' curso.id %}"> ← Regresar</a>
</div>

<div class="contenedor-central">
  <div class="container">
    <h1>Estadísticas Generales Curso</h1>

    <form method="get">
      <div>
        <label for="nivel">Nivel:</label><br>
        <select name="nivel" id="nivel">
          <option value="">Todos</option>
          <option value="1" {% if request.GET.nivel == '1' %}selected{% endif %}>Nivel 1</option>
          <option value="2" {% if request.GET.nivel == '2' %}selected{% endif %}>Nivel 2</option>
          <option value="3" {% if request.GET.nivel == '3' %}selected{% endif %}>Nivel 3</option>
          <option value="4" {% if request.GET.nivel == '4' %}selected{% endif %}>Nivel 4</option>
          <option value="5" {% if request.GET.nivel == '5' %}selected{% endif %}>Nivel 5</option>
        </select>
      </div>
      <div>
        <label for="fecha">Desde:</label><br>
        <input type="date" name="fecha_i" id="fecha_i" value="{{ request.GET.fecha_i }}">
      </div>
      <div>
        <label for="fecha">Hasta:</label><br>
        <input type="date" name="fecha_f" id="fecha_f" value="{{ request.GET.fecha_f }}">
      </div>
      <div>
        <button type="submit">Filtrar</button>
      </div>
    </form>

    <div class="resultados">
      {% if reportes %}
        <div class="graficas-row">
          <div id="grafico_Distraccion_Somnolencia" style="height: 300px; flex: 1;"></div>
          <div id="grafica_puntajes" style="height: 300px; flex: 1;"></div>
        </div>

        <h2>Promedio puntaje: {{ promedio_puntaje }}</h2>

        <div class="graficas-row">
          <div id="grafica_distracciones" style="height: 300px; flex: 1;"></div>
          <div id="grafico_Distraccion_Tiempos" style="height: 300px; flex: 1;"></div>
        </div>

        <h2>Total distracciones: {{ total_distracciones }}</h2>
        <h2>Promedio distracciones: {{ promedio_distracciones }}</h2>
        <h2>Promedio tiempo distracciones: {{ promedio_tiempo_distraccion }}</h2>

        <div class="graficas-row">
          <div id="grafica_somnolencias" style="height: 300px; flex: 1;"></div>
          <div id="grafico_Somnolencia_Tiempos" style="height: 300px; flex: 1;"></div>
        </div>

        <h2>Total somnolencias: {{ total_somnolencias }}</h2>
        <h2>Promedio somnolencias: {{ promedio_somnolencias }}</h2>
        <h2>Promedio tiempo somnolencia: {{ promedio_tiempo_somnolencia }}</h2>
      {% else %}
        <p>No hay reportes que coincidan con los filtros.</p>
        <p>Curso ID: {{ curso.id }}</p>
      {% endif %}
    </div>
  </div>
</div>

</body>
<script>
  const puntajes = {{ puntajes|safe }};
  const distracciones = {{ distracciones|safe }};
  const somnolencias = {{ somnolencias|safe }};
  const graficodis_som = {{ graficodis_som|safe }};
  const distraccion_data = {{ tiempos_distraccion_sumados|safe }};
  const somnolencia_data = {{ tiempos_somnolencia_sumados|safe }};
  window.addEventListener('DOMContentLoaded', () => {
    if (puntajes.length > 0) {
      renderGraficoLineasPuntaje(puntajes, "#grafica_puntajes");
      renderGraficoLineasDistraccionGeneral(distracciones, "#grafica_distracciones");
      renderGraficoLineasSomnolenciaGeneral(somnolencias, "#grafica_somnolencias");
      renderGraficoPastelReporte(graficodis_som, "#grafico_Distraccion_Somnolencia");
      renderGraficoLineasTiemposDisGeneral(distraccion_data, "#grafico_Distraccion_Tiempos");
      renderGraficoLineasTiemposSomGeneral(somnolencia_data, "#grafico_Somnolencia_Tiempos");
    }
  });
</script>
</html>

PROFESOR/templates/reporte_niño.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Dashboard Padre - Eduflex</title>
  <link rel="stylesheet" href="{% static 'css/report_total.css' %}">
</head>
<body>

<header>
  <img src="{% static 'img/logo.png' %}" alt="Logo" class="logo">
  <a href="{% url 'profesor:dashboardTeacher' %}" class="btn-nav">Home</a>
  <a href="{% url 'accounts:logout' %}" class="btn-cerrar">Cerrar sesión</a>
</header>

<div class="regresar">
   <a href="{% url 'profesor:curso' curso.id %}" class="boton-recuperar">← Regresar</a>
</div>


<main>

  <section class="estudiante ">
    <div class="contenido-reportes">
        <h4 >Reportes:</h4>
        <a href="{% url 'profesor:verEstadisticasNiño' nino.id curso.id %}" class="btn">Estadistiocas generales niño</a>

        <div class="reportes">
          {% for reporte in reportes %}
          <a class="card reporte" href="{% url 'profesor:verReportStudent' reporte.id curso.id %}">
            <strong></strong>
             <span>{{ reporte.titulo }}</span>
            <span>Duración:{{ reporte.duracion_evaluacion }}</span>
            <span>Fecha:{{ reporte.fecha }}</span>
          </a>
          {% endfor %}
        </div>
    </div>
  </section>
</main>
</body>
</html>